"use client";

/**
 * ComplianceBanner — Visually unmissable amber warning banner for
 * is_rule_validated: false results. Also handles VALIDATED (green) and
 * BLOCKED (red) states.
 *
 * FR requirement: "Prominent, correctly-styled amber banner — must be visually
 * unmissable, not a small footnote."
 */

interface ComplianceBannerProps {
  type: "WARNING" | "VALIDATED" | "BLOCKED";
  label?: string;
  message?: string;
  className?: string;
}

const CONFIGS = {
  WARNING: {
    bg:      "rgba(245,158,11,0.08)",
    border:  "rgba(245,158,11,0.35)",
    iconBg:  "rgba(245,158,11,0.15)",
    iconStroke: "#f59e0b",
    labelColor: "#fbbf24",
    msgColor:   "#fde68a",
    defaultLabel:   "Illustrative — Not Yet Rule-Validated",
    defaultMessage: "This output was generated by general AI analysis and has not been verified against specific statutes or regulations for this corridor. Do not rely on it for compliance decisions without engaging qualified local counsel.",
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
        <line x1="12" y1="9" x2="12" y2="13"/>
        <line x1="12" y1="17" x2="12.01" y2="17"/>
      </svg>
    ),
  },
  VALIDATED: {
    bg:      "rgba(52,211,153,0.06)",
    border:  "rgba(52,211,153,0.25)",
    iconBg:  "rgba(52,211,153,0.12)",
    iconStroke: "#34d399",
    labelColor: "#6ee7b7",
    msgColor:   "#a7f3d0",
    defaultLabel:   "Rule-Validated",
    defaultMessage: "This structure was evaluated against applicable Rego policies for the recognised corridor. Results are deterministic.",
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
        <polyline points="9 12 11 14 15 10"/>
      </svg>
    ),
  },
  BLOCKED: {
    bg:      "rgba(248,113,113,0.07)",
    border:  "rgba(248,113,113,0.3)",
    iconBg:  "rgba(248,113,113,0.12)",
    iconStroke: "#f87171",
    labelColor: "#fca5a5",
    msgColor:   "#fecaca",
    defaultLabel:   "Compliance Block — Structure Not Permitted",
    defaultMessage: "One or more deterministic Rego rules identified a compliance block for this structure. Review the specific violations before proceeding.",
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <circle cx="12" cy="12" r="10"/>
        <line x1="4.93" y1="4.93" x2="19.07" y2="19.07"/>
      </svg>
    ),
  },
};

export function ComplianceBanner({ type, label, message, className = "" }: ComplianceBannerProps) {
  const cfg = CONFIGS[type];

  return (
    <div
      role="alert"
      className={`flex items-start gap-4 rounded-xl p-4 ${className}`}
      style={{
        background: cfg.bg,
        border: `1.5px solid ${cfg.border}`,
      }}
    >
      {/* Icon */}
      <div
        className="shrink-0 w-10 h-10 rounded-lg flex items-center justify-center mt-0.5"
        style={{ background: cfg.iconBg, color: cfg.iconStroke }}
      >
        {cfg.icon}
      </div>

      {/* Content */}
      <div className="flex-1 min-w-0">
        <p className="text-sm font-bold tracking-wide uppercase" style={{ color: cfg.labelColor }}>
          {label ?? cfg.defaultLabel}
        </p>
        <p className="mt-1 text-sm leading-relaxed" style={{ color: cfg.msgColor }}>
          {message ?? cfg.defaultMessage}
        </p>
      </div>
    </div>
  );
}

/** Compact inline badge version — used inside structure cards */
export function CompliancePill({ isRuleValidated, isAllowed }: { isRuleValidated: boolean; isAllowed?: boolean }) {
  if (!isRuleValidated) {
    return (
      <span
        className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold"
        style={{ background: "rgba(245,158,11,0.12)", color: "#fbbf24" }}
      >
        <span className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse" />
        Illustrative
      </span>
    );
  }
  if (isAllowed) {
    return (
      <span
        className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold"
        style={{ background: "rgba(52,211,153,0.1)", color: "#34d399" }}
      >
        <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
        Validated ✓
      </span>
    );
  }
  return (
    <span
      className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold"
      style={{ background: "rgba(248,113,113,0.1)", color: "#f87171" }}
    >
      <span className="w-1.5 h-1.5 rounded-full bg-red-400" />
      Blocked
    </span>
  );
}
