"use client";

/**
 * DiagramPanel — Full diagram panel with:
 *  - Mermaid.js client-side rendering (zero backend at render time)
 *  - Export to PNG (SVG → canvas → PNG blob, canvas API only, no library)
 *  - Export to PDF (browser Print API on isolated SVG, no library)
 *  - Warning banner for illustrative / fallback diagrams
 *  - Metadata bar: entity count, edge count, regulatory checkpoints, jurisdictions
 *
 * FR-5.2: Both exports are entirely client-side — no backend involved post-generation.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { MermaidDiagram } from "./MermaidDiagram";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface DiagramData {
  mermaid_syntax: string;
  entity_count: number;
  edge_count: number;
  regulatory_checkpoint_count: number;
  jurisdictions: string[];
  structure_name: string;
  generation_warnings: string[];
}

interface DiagramPanelProps {
  diagram: DiagramData;
  isIllustrative?: boolean; // show WARNING banner?
  className?: string;
}

// ── Export helpers (pure client-side, FR-5.2) ─────────────────────────────────

async function exportToPng(svgEl: SVGSVGElement, filename: string): Promise<void> {
  // 1. Serialize the SVG
  const serializer = new XMLSerializer();
  let svgStr = serializer.serializeToString(svgEl);

  // 2. Ensure proper XML namespace
  if (!svgStr.includes("xmlns=")) {
    svgStr = svgStr.replace("<svg", '<svg xmlns="http://www.w3.org/2000/svg"');
  }

  // 3. Determine dimensions
  const w = parseFloat(svgEl.getAttribute("width") || "0") || svgEl.viewBox?.baseVal?.width || 900;
  const h = parseFloat(svgEl.getAttribute("height") || "0") || svgEl.viewBox?.baseVal?.height || 600;
  const scale = 2; // retina quality

  // 4. Draw to canvas
  const canvas = document.createElement("canvas");
  canvas.width = w * scale;
  canvas.height = h * scale;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas 2D context unavailable");

  // Dark background matching the UI theme
  ctx.fillStyle = "#0f1220";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.scale(scale, scale);

  const blob = new Blob([svgStr], { type: "image/svg+xml;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  await new Promise<void>((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      ctx.drawImage(img, 0, 0);
      URL.revokeObjectURL(url);
      // Trigger download
      canvas.toBlob((pngBlob) => {
        if (!pngBlob) { reject(new Error("Canvas PNG export failed")); return; }
        const a = document.createElement("a");
        a.href = URL.createObjectURL(pngBlob);
        a.download = filename;
        a.click();
        setTimeout(() => URL.revokeObjectURL(a.href), 3000);
        resolve();
      }, "image/png");
    };
    img.onerror = () => { URL.revokeObjectURL(url); reject(new Error("SVG image load failed")); };
    img.src = url;
  });
}

function exportToPdf(svgEl: SVGSVGElement, title: string): void {
  // Use browser Print API on an isolated window containing only the SVG
  // No jsPDF or external library needed — FR-5.2 compliant
  const serializer = new XMLSerializer();
  let svgStr = serializer.serializeToString(svgEl);
  if (!svgStr.includes("xmlns=")) {
    svgStr = svgStr.replace("<svg", '<svg xmlns="http://www.w3.org/2000/svg"');
  }

  const w = parseFloat(svgEl.getAttribute("width") || "0") || 900;
  const h = parseFloat(svgEl.getAttribute("height") || "0") || 600;

  const printWindow = window.open("", "_blank", "width=1000,height=700");
  if (!printWindow) {
    alert("Please allow pop-ups to export PDF, then try again.");
    return;
  }

  printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${title} — Sententia.ai</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #0f1220; display: flex; flex-direction: column; align-items: center; padding: 32px; font-family: 'Inter', sans-serif; }
    h1 { color: #818cf8; font-size: 18px; font-weight: 600; margin-bottom: 8px; }
    p.meta { color: #64748b; font-size: 12px; margin-bottom: 24px; }
    .svg-wrapper { background: #131929; border-radius: 12px; padding: 24px; border: 1px solid rgba(255,255,255,0.07); }
    svg { max-width: 100%; height: auto; }
    @media print {
      body { background: white !important; }
      .svg-wrapper { background: white !important; border: none; }
      h1 { color: #1e3a5f !important; }
      p.meta { color: #64748b !important; }
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p class="meta">Generated by Sententia.ai · ${new Date().toLocaleDateString()}</p>
  <div class="svg-wrapper">${svgStr}</div>
  <script>
    window.onload = function() { window.print(); };
  </script>
</body>
</html>`);
  printWindow.document.close();
}

// ── Component ─────────────────────────────────────────────────────────────────

export function DiagramPanel({ diagram, isIllustrative = false, className = "" }: DiagramPanelProps) {
  const svgRef = useRef<SVGSVGElement | null>(null);
  const [exportState, setExportState] = useState<"idle" | "exporting">("idle");
  const [exportError, setExportError] = useState<string | null>(null);
  const [isExpanded, setIsExpanded]   = useState(false);
  const [zoom, setZoom]               = useState(1.0);
  const [showCode, setShowCode]       = useState(false);
  const [copiedCode, setCopiedCode]   = useState(false);

  const zoomIn    = () => setZoom((z) => Math.min(+(z + 0.15).toFixed(2), 2.2));
  const zoomOut   = () => setZoom((z) => Math.max(+(z - 0.15).toFixed(2), 0.5));
  const resetZoom = () => setZoom(1.0);

  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") setIsExpanded(false);
    }
    if (isExpanded) {
      window.addEventListener("keydown", handleKeyDown);
      document.body.style.overflow = "hidden";
    }
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      document.body.style.overflow = "";
      setZoom(1.0); // Reset zoom on close
    };
  }, [isExpanded]);

  const handleSvgReady = useCallback((svgEl: SVGSVGElement) => {
    svgRef.current = svgEl;
  }, []);

  const safeName = diagram.structure_name || "sententia-structure";
  const fileSlug = safeName.replace(/[^a-z0-9]/gi, "-").toLowerCase().slice(0, 40);

  async function handleExportPng() {
    if (!svgRef.current) { setExportError("Diagram not rendered yet — wait a moment and retry."); return; }
    setExportState("exporting");
    setExportError(null);
    try {
      await exportToPng(svgRef.current, `${fileSlug}.png`);
    } catch (e) {
      setExportError(e instanceof Error ? e.message : "PNG export failed");
    } finally {
      setExportState("idle");
    }
  }

  function handleExportPdf() {
    if (!svgRef.current) { setExportError("Diagram not rendered yet — wait a moment and retry."); return; }
    setExportError(null);
    exportToPdf(svgRef.current, diagram.structure_name || "Structure Diagram");
  }

  function handleCopyCode() {
    navigator.clipboard.writeText(diagram.mermaid_syntax);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  }

  return (
    <>
      <div
        className={`rounded-2xl overflow-hidden ${className}`}
        style={{
          background: "rgba(15,18,30,0.8)",
          border: "1px solid rgba(255,255,255,0.08)",
          boxShadow: "0 8px 32px rgba(0,0,0,0.45)",
        }}
      >
        {/* ── Header bar ── */}
        <div
          className="flex flex-wrap items-center justify-between gap-2 px-5 py-3.5"
          style={{
            borderBottom: "1px solid rgba(255,255,255,0.06)",
            background: "rgba(255,255,255,0.02)",
          }}
        >
          <div className="flex items-center gap-2.5">
            {/* Diagram icon */}
            <div className="p-1.5 rounded-lg bg-indigo-500/10 border border-indigo-500/20 text-indigo-400">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                <rect x="3" y="3" width="6" height="6" rx="1"/>
                <rect x="15" y="3" width="6" height="6" rx="1"/>
                <rect x="9" y="15" width="6" height="6" rx="1"/>
                <path d="M6 9v3a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V9"/>
              </svg>
            </div>
            <span className="text-sm font-semibold text-slate-200">
              {diagram.structure_name || "Structure Diagram"}
            </span>
          </div>

          {/* Export & View toolbar */}
          <div className="flex items-center gap-2">
            {/* Zoom Controls */}
            <div
              className="flex items-center gap-0.5 px-1.5 py-0.5 rounded-lg text-xs"
              style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}
            >
              <button
                onClick={zoomOut}
                title="Zoom Out"
                className="p-1 rounded transition-colors hover:bg-white/10 text-slate-400 hover:text-slate-200"
              >
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <line x1="5" y1="12" x2="19" y2="12"/>
                </svg>
              </button>
              <button
                onClick={resetZoom}
                title="Reset Zoom"
                className="px-1.5 font-mono text-[11px] text-indigo-300 hover:text-indigo-200"
              >
                {Math.round(zoom * 100)}%
              </button>
              <button
                onClick={zoomIn}
                title="Zoom In"
                className="p-1 rounded transition-colors hover:bg-white/10 text-slate-400 hover:text-slate-200"
              >
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <line x1="12" y1="5" x2="12" y2="19"/>
                  <line x1="5" y1="12" x2="19" y2="12"/>
                </svg>
              </button>
            </div>

            {/* Toggle Code button */}
            <button
              onClick={() => setShowCode(!showCode)}
              title="Toggle Raw Code"
              className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs font-mono transition-all"
              style={{
                background: showCode ? "rgba(168,85,247,0.2)" : "rgba(255,255,255,0.05)",
                border: "1px solid " + (showCode ? "rgba(168,85,247,0.4)" : "rgba(255,255,255,0.1)"),
                color: showCode ? "#c084fc" : "#94a3b8",
                cursor: "pointer",
              }}
            >
              &lt;/&gt;
            </button>

            {/* Expand button */}
            <button
              onClick={() => setIsExpanded(true)}
              title="Expand to Full View"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all"
              style={{
                background: "rgba(129,140,248,0.12)",
                border: "1px solid rgba(129,140,248,0.25)",
                color: "#c7d2fe",
                cursor: "pointer",
              }}
              onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = "rgba(129,140,248,0.22)"; }}
              onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = "rgba(129,140,248,0.12)"; }}
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true">
                <polyline points="15 3 21 3 21 9"/>
                <polyline points="9 21 3 21 3 15"/>
                <line x1="21" y1="3" x2="14" y2="10"/>
                <line x1="3" y1="21" x2="10" y2="14"/>
              </svg>
              Expand
            </button>

            {/* PNG export */}
            <button
              id="btn-export-png"
              onClick={handleExportPng}
              disabled={exportState === "exporting"}
              title="Export as PNG"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all"
              style={{
                background: "rgba(99,102,241,0.12)",
                border: "1px solid rgba(99,102,241,0.25)",
                color: "#a5b4fc",
                cursor: exportState === "exporting" ? "not-allowed" : "pointer",
                opacity: exportState === "exporting" ? 0.6 : 1,
              }}
              onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = "rgba(99,102,241,0.22)"; }}
              onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = "rgba(99,102,241,0.12)"; }}
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
              </svg>
              {exportState === "exporting" ? "Exporting…" : "PNG"}
            </button>

            {/* PDF export */}
            <button
              id="btn-export-pdf"
              onClick={handleExportPdf}
              title="Export as PDF"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all"
              style={{
                background: "rgba(52,211,153,0.08)",
                border: "1px solid rgba(52,211,153,0.2)",
                color: "#6ee7b7",
                cursor: "pointer",
              }}
              onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = "rgba(52,211,153,0.16)"; }}
              onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = "rgba(52,211,153,0.08)"; }}
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/>
              </svg>
              PDF
            </button>
          </div>
        </div>

        {/* ── Generation warnings ── */}
        {diagram.generation_warnings.length > 0 && (
          <div
            className="px-5 py-2"
            style={{
              background: "rgba(251,191,36,0.04)",
              borderBottom: "1px solid rgba(251,191,36,0.1)",
            }}
          >
            {diagram.generation_warnings.map((w, i) => (
              <p key={i} className="text-xs" style={{ color: "#fbbf24" }}>
                ⚠ {w}
              </p>
            ))}
          </div>
        )}

        {/* ── Main Diagram Canvas / Code View ── */}
        {showCode ? (
          <div className="p-4 bg-slate-950/80 font-mono text-xs text-slate-300 overflow-x-auto relative min-h-[220px] max-h-[340px]">
            <div className="flex justify-between items-center mb-2 pb-2 border-b border-white/10 text-slate-400">
              <span>Mermaid.js Definition</span>
              <button
                onClick={handleCopyCode}
                className="px-2.5 py-1 rounded bg-white/10 hover:bg-white/20 text-xs text-slate-200 transition-colors"
              >
                {copiedCode ? "✓ Copied" : "Copy Syntax"}
              </button>
            </div>
            <pre className="text-indigo-200/90 leading-relaxed overflow-auto">{diagram.mermaid_syntax}</pre>
          </div>
        ) : (
          <div
            className="p-4 cursor-pointer relative group rounded-xl transition-all overflow-hidden flex items-center justify-center min-h-[240px] max-h-[360px]"
            style={{
              background: "radial-gradient(circle, rgba(129,140,248,0.08) 1px, transparent 1px) 0 0 / 22px 22px, #0b0e17",
            }}
            onClick={() => setIsExpanded(true)}
            title="Click to view full screen diagram"
          >
            {/* Expand Hover Badge */}
            <div
              className="absolute top-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity text-xs px-2.5 py-1 rounded-lg pointer-events-none z-10 flex items-center gap-1.5 shadow-lg"
              style={{ background: "rgba(99,102,241,0.9)", color: "#ffffff" }}
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <polyline points="15 3 21 3 21 9"/>
                <polyline points="9 21 3 21 3 15"/>
              </svg>
              Click to expand
            </div>

            {/* Canvas zoom wrapper */}
            <div
              className="w-full h-full flex items-center justify-center transition-transform duration-150 ease-out"
              style={{ transform: `scale(${zoom})`, transformOrigin: "center center" }}
            >
              <MermaidDiagram
                syntax={diagram.mermaid_syntax}
                theme="dark"
                maxHeight="320px"
                onSvgReady={handleSvgReady}
                className="w-full"
              />
            </div>
          </div>
        )}

        {/* ── Export error ── */}
        {exportError && (
          <div
            className="mx-5 mb-3 px-4 py-2 rounded-xl text-xs"
            style={{
              background: "rgba(248,113,113,0.08)",
              border: "1px solid rgba(248,113,113,0.2)",
              color: "#fca5a5",
            }}
          >
            {exportError}
          </div>
        )}

        {/* ── Metadata bar ── */}
        <div
          className="flex flex-wrap items-center justify-between gap-y-1.5 px-5 py-3"
          style={{ borderTop: "1px solid rgba(255,255,255,0.05)" }}
        >
          <div className="flex flex-wrap items-center gap-x-6 gap-y-1.5">
            <MetaBadge icon="□" label="Entities" value={diagram.entity_count} color="#818cf8" />
            <MetaBadge icon="→" label="Flows" value={diagram.edge_count} color="#38bdf8" />
            <MetaBadge icon="◆" label="Checkpoints" value={diagram.regulatory_checkpoint_count} color="#fb923c" />
            {diagram.jurisdictions.length > 0 && (
              <span className="text-xs text-slate-400">
                {diagram.jurisdictions.join(" · ")}
              </span>
            )}
          </div>
          <button
            onClick={() => setIsExpanded(true)}
            className="text-xs transition-colors hover:underline text-indigo-400 hover:text-indigo-300"
          >
            Expand View ↗
          </button>
        </div>
      </div>

      {/* ── Fullscreen Overlay Modal ── */}
      {isExpanded && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 md:p-8"
          style={{ background: "rgba(5, 7, 15, 0.88)", backdropFilter: "blur(16px)" }}
          onClick={() => setIsExpanded(false)}
        >
          <div
            className="relative flex flex-col w-full max-w-6xl h-[88vh] rounded-2xl overflow-hidden shadow-2xl"
            style={{
              background: "#0d111c",
              border: "1px solid rgba(255,255,255,0.12)",
              boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.85)",
            }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div
              className="flex items-center justify-between px-6 py-4"
              style={{
                borderBottom: "1px solid rgba(255,255,255,0.08)",
                background: "rgba(255,255,255,0.02)",
              }}
            >
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="3" y="3" width="6" height="6" rx="1"/>
                    <rect x="15" y="3" width="6" height="6" rx="1"/>
                    <rect x="9" y="15" width="6" height="6" rx="1"/>
                    <path d="M6 9v3a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V9"/>
                  </svg>
                </div>
                <div>
                  <h3 className="text-base font-bold text-slate-100">
                    {diagram.structure_name || "Structure Diagram"}
                  </h3>
                  <p className="text-xs text-slate-400">
                    Interactive multi-jurisdiction ownership architecture
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-3">
                {/* Zoom controls inside modal */}
                <div
                  className="flex items-center gap-1 px-2.5 py-1 rounded-xl text-xs"
                  style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}
                >
                  <button
                    onClick={zoomOut}
                    title="Zoom Out (-)"
                    className="p-1 rounded-md transition-colors hover:bg-white/10 text-slate-400"
                  >
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <line x1="5" y1="12" x2="19" y2="12"/>
                    </svg>
                  </button>
                  <button
                    onClick={resetZoom}
                    title="Reset Zoom (Fit)"
                    className="px-2 font-mono text-xs text-indigo-300 hover:text-white"
                  >
                    {Math.round(zoom * 100)}%
                  </button>
                  <button
                    onClick={zoomIn}
                    title="Zoom In (+)"
                    className="p-1 rounded-md transition-colors hover:bg-white/10 text-slate-400"
                  >
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <line x1="12" y1="5" x2="12" y2="19"/>
                      <line x1="5" y1="12" x2="19" y2="12"/>
                    </svg>
                  </button>
                </div>

                <button
                  onClick={handleExportPng}
                  disabled={exportState === "exporting"}
                  className="px-3.5 py-1.5 rounded-lg text-xs font-medium transition-all"
                  style={{
                    background: "rgba(99,102,241,0.15)",
                    border: "1px solid rgba(99,102,241,0.3)",
                    color: "#a5b4fc",
                  }}
                >
                  PNG
                </button>
                <button
                  onClick={handleExportPdf}
                  className="px-3.5 py-1.5 rounded-lg text-xs font-medium transition-all"
                  style={{
                    background: "rgba(52,211,153,0.12)",
                    border: "1px solid rgba(52,211,153,0.25)",
                    color: "#6ee7b7",
                  }}
                >
                  PDF
                </button>
                <button
                  onClick={() => setIsExpanded(false)}
                  className="p-2 rounded-xl transition-colors hover:bg-white/10 text-slate-400 hover:text-slate-100 ml-1"
                  title="Close (Esc)"
                >
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <line x1="18" y1="6" x2="6" y2="18"/>
                    <line x1="6" y1="6" x2="18" y2="18"/>
                  </svg>
                </button>
              </div>
            </div>

            {/* Modal Canvas */}
            <div
              className="flex-1 p-8 overflow-auto flex items-center justify-center relative min-h-[400px]"
              style={{
                background: "radial-gradient(circle, rgba(129,140,248,0.1) 1px, transparent 1px) 0 0 / 28px 28px, #080b13",
              }}
            >
              <div
                className="w-full h-full flex items-center justify-center transition-transform duration-150 ease-out"
                style={{ transform: `scale(${zoom})`, transformOrigin: "center center" }}
              >
                <MermaidDiagram
                  syntax={diagram.mermaid_syntax}
                  theme="dark"
                  maxHeight="70vh"
                  onSvgReady={handleSvgReady}
                  className="w-full max-w-4xl"
                />
              </div>
            </div>

            {/* Modal Footer */}
            <div
              className="flex items-center justify-between px-6 py-3.5"
              style={{ borderTop: "1px solid rgba(255,255,255,0.06)", background: "rgba(255,255,255,0.01)" }}
            >
              <div className="flex items-center gap-6">
                <MetaBadge icon="□" label="Entities" value={diagram.entity_count} color="#818cf8" />
                <MetaBadge icon="→" label="Flows" value={diagram.edge_count} color="#38bdf8" />
                <MetaBadge icon="◆" label="Checkpoints" value={diagram.regulatory_checkpoint_count} color="#fb923c" />
                {diagram.jurisdictions.length > 0 && (
                  <span className="text-xs text-slate-400">
                    {diagram.jurisdictions.join(" · ")}
                  </span>
                )}
              </div>
              <span className="text-xs text-slate-500">
                Press Esc or click ✕ to exit preview
              </span>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

function MetaBadge({
  icon,
  label,
  value,
  color,
}: {
  icon: string;
  label: string;
  value: number;
  color: string;
}) {
  return (
    <div className="flex items-center gap-1.5">
      <span style={{ color, fontSize: "11px" }}>{icon}</span>
      <span className="text-xs" style={{ color: "#64748b" }}>
        {label}:
      </span>
      <span className="text-xs font-semibold" style={{ color: "#94a3b8" }}>
        {value}
      </span>
    </div>
  );
}

