"use client";

/**
 * DisclaimerBanner — FR-6.4
 *
 * The standard disclaimer must appear on EVERY output view:
 * "Analytical aid, not a substitute for independent legal advice."
 *
 * Two variants:
 *   - <DisclaimerBanner />           → full-width bar (default for page footers)
 *   - <DisclaimerBanner compact />   → small inline version for cards
 */

interface DisclaimerBannerProps {
  compact?: boolean;
  className?: string;
}

const DISCLAIMER_TEXT =
  "Sententia.ai outputs are analytical aids generated by artificial intelligence and do not constitute legal advice, tax advice, or regulatory guidance. " +
  "They are not a substitute for independent advice from qualified legal, tax, and regulatory counsel in each relevant jurisdiction. " +
  "Always verify outputs against current statutes and consult licensed practitioners before making investment or structuring decisions.";

export function DisclaimerBanner({ compact = false, className = "" }: DisclaimerBannerProps) {
  if (compact) {
    return (
      <div
        className={`flex items-start gap-2 px-3 py-2 rounded-lg ${className}`}
        style={{ background: "rgba(100,116,139,0.06)", border: "1px solid rgba(100,116,139,0.15)" }}
      >
        <svg
          width="13"
          height="13"
          viewBox="0 0 24 24"
          fill="none"
          stroke="#64748b"
          strokeWidth="2"
          className="shrink-0 mt-0.5"
          aria-hidden="true"
        >
          <circle cx="12" cy="12" r="10"/>
          <line x1="12" y1="8" x2="12" y2="12"/>
          <line x1="12" y1="16" x2="12.01" y2="16"/>
        </svg>
        <p className="text-xs leading-relaxed" style={{ color: "#64748b" }}>
          <strong className="text-slate-400">FR-6.4 Disclaimer: </strong>
          Analytical aid only — not legal advice. Verify with qualified counsel.
        </p>
      </div>
    );
  }

  return (
    <div
      className={`w-full px-5 py-4 ${className}`}
      style={{
        background:   "rgba(255,255,255,0.015)",
        borderTop:    "1px solid rgba(255,255,255,0.06)",
      }}
      role="note"
      aria-label="Legal disclaimer"
    >
      <div className="max-w-screen-xl mx-auto flex items-start gap-3">
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="#475569"
          strokeWidth="1.5"
          className="shrink-0 mt-0.5"
          aria-hidden="true"
        >
          <circle cx="12" cy="12" r="10"/>
          <line x1="12" y1="8" x2="12" y2="12"/>
          <line x1="12" y1="16" x2="12.01" y2="16"/>
        </svg>
        <p className="text-xs leading-relaxed" style={{ color: "#475569" }}>
          <strong className="font-semibold" style={{ color: "#64748b" }}>Legal Disclaimer (FR-6.4): </strong>
          {DISCLAIMER_TEXT}
        </p>
      </div>
    </div>
  );
}
